# site details
title: YAML is not a programming language
tag_line: YAML is not a programming language
description: YAML is not programming language
keywords: 
url: https://yamlisnotaprogramminglanguage.com/
author: Mircea Ulinic
author_url: https://mirceaulinic.net/

# tech
markdown: kramdown


theme: jekyll-theme-hacker
